require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CheersController do

  # This should return the minimal set of attributes required to create a valid
  # Cheer. As you add validations to Cheer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CheersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cheers as @cheers" do
      cheer = Cheer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cheers).should eq([cheer])
    end
  end

  describe "GET show" do
    it "assigns the requested cheer as @cheer" do
      cheer = Cheer.create! valid_attributes
      get :show, {:id => cheer.to_param}, valid_session
      assigns(:cheer).should eq(cheer)
    end
  end

  describe "GET new" do
    it "assigns a new cheer as @cheer" do
      get :new, {}, valid_session
      assigns(:cheer).should be_a_new(Cheer)
    end
  end

  describe "GET edit" do
    it "assigns the requested cheer as @cheer" do
      cheer = Cheer.create! valid_attributes
      get :edit, {:id => cheer.to_param}, valid_session
      assigns(:cheer).should eq(cheer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cheer" do
        expect {
          post :create, {:cheer => valid_attributes}, valid_session
        }.to change(Cheer, :count).by(1)
      end

      it "assigns a newly created cheer as @cheer" do
        post :create, {:cheer => valid_attributes}, valid_session
        assigns(:cheer).should be_a(Cheer)
        assigns(:cheer).should be_persisted
      end

      it "redirects to the created cheer" do
        post :create, {:cheer => valid_attributes}, valid_session
        response.should redirect_to(Cheer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cheer as @cheer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cheer.any_instance.stub(:save).and_return(false)
        post :create, {:cheer => { "title" => "invalid value" }}, valid_session
        assigns(:cheer).should be_a_new(Cheer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cheer.any_instance.stub(:save).and_return(false)
        post :create, {:cheer => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cheer" do
        cheer = Cheer.create! valid_attributes
        # Assuming there are no other cheers in the database, this
        # specifies that the Cheer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cheer.any_instance.should_receive(:update).with({ "title" => "MyText" })
        put :update, {:id => cheer.to_param, :cheer => { "title" => "MyText" }}, valid_session
      end

      it "assigns the requested cheer as @cheer" do
        cheer = Cheer.create! valid_attributes
        put :update, {:id => cheer.to_param, :cheer => valid_attributes}, valid_session
        assigns(:cheer).should eq(cheer)
      end

      it "redirects to the cheer" do
        cheer = Cheer.create! valid_attributes
        put :update, {:id => cheer.to_param, :cheer => valid_attributes}, valid_session
        response.should redirect_to(cheer)
      end
    end

    describe "with invalid params" do
      it "assigns the cheer as @cheer" do
        cheer = Cheer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cheer.any_instance.stub(:save).and_return(false)
        put :update, {:id => cheer.to_param, :cheer => { "title" => "invalid value" }}, valid_session
        assigns(:cheer).should eq(cheer)
      end

      it "re-renders the 'edit' template" do
        cheer = Cheer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cheer.any_instance.stub(:save).and_return(false)
        put :update, {:id => cheer.to_param, :cheer => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cheer" do
      cheer = Cheer.create! valid_attributes
      expect {
        delete :destroy, {:id => cheer.to_param}, valid_session
      }.to change(Cheer, :count).by(-1)
    end

    it "redirects to the cheers list" do
      cheer = Cheer.create! valid_attributes
      delete :destroy, {:id => cheer.to_param}, valid_session
      response.should redirect_to(cheers_url)
    end
  end

end
