require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PoemPagesController do

  # This should return the minimal set of attributes required to create a valid
  # PoemPage. As you add validations to PoemPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PoemPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all poem_pages as @poem_pages" do
      poem_page = PoemPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:poem_pages).should eq([poem_page])
    end
  end

  describe "GET show" do
    it "assigns the requested poem_page as @poem_page" do
      poem_page = PoemPage.create! valid_attributes
      get :show, {:id => poem_page.to_param}, valid_session
      assigns(:poem_page).should eq(poem_page)
    end
  end

  describe "GET new" do
    it "assigns a new poem_page as @poem_page" do
      get :new, {}, valid_session
      assigns(:poem_page).should be_a_new(PoemPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested poem_page as @poem_page" do
      poem_page = PoemPage.create! valid_attributes
      get :edit, {:id => poem_page.to_param}, valid_session
      assigns(:poem_page).should eq(poem_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PoemPage" do
        expect {
          post :create, {:poem_page => valid_attributes}, valid_session
        }.to change(PoemPage, :count).by(1)
      end

      it "assigns a newly created poem_page as @poem_page" do
        post :create, {:poem_page => valid_attributes}, valid_session
        assigns(:poem_page).should be_a(PoemPage)
        assigns(:poem_page).should be_persisted
      end

      it "redirects to the created poem_page" do
        post :create, {:poem_page => valid_attributes}, valid_session
        response.should redirect_to(PoemPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved poem_page as @poem_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        PoemPage.any_instance.stub(:save).and_return(false)
        post :create, {:poem_page => { "number" => "invalid value" }}, valid_session
        assigns(:poem_page).should be_a_new(PoemPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PoemPage.any_instance.stub(:save).and_return(false)
        post :create, {:poem_page => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested poem_page" do
        poem_page = PoemPage.create! valid_attributes
        # Assuming there are no other poem_pages in the database, this
        # specifies that the PoemPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PoemPage.any_instance.should_receive(:update).with({ "number" => "1" })
        put :update, {:id => poem_page.to_param, :poem_page => { "number" => "1" }}, valid_session
      end

      it "assigns the requested poem_page as @poem_page" do
        poem_page = PoemPage.create! valid_attributes
        put :update, {:id => poem_page.to_param, :poem_page => valid_attributes}, valid_session
        assigns(:poem_page).should eq(poem_page)
      end

      it "redirects to the poem_page" do
        poem_page = PoemPage.create! valid_attributes
        put :update, {:id => poem_page.to_param, :poem_page => valid_attributes}, valid_session
        response.should redirect_to(poem_page)
      end
    end

    describe "with invalid params" do
      it "assigns the poem_page as @poem_page" do
        poem_page = PoemPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PoemPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => poem_page.to_param, :poem_page => { "number" => "invalid value" }}, valid_session
        assigns(:poem_page).should eq(poem_page)
      end

      it "re-renders the 'edit' template" do
        poem_page = PoemPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PoemPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => poem_page.to_param, :poem_page => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested poem_page" do
      poem_page = PoemPage.create! valid_attributes
      expect {
        delete :destroy, {:id => poem_page.to_param}, valid_session
      }.to change(PoemPage, :count).by(-1)
    end

    it "redirects to the poem_pages list" do
      poem_page = PoemPage.create! valid_attributes
      delete :destroy, {:id => poem_page.to_param}, valid_session
      response.should redirect_to(poem_pages_url)
    end
  end

end
