require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe YbClassesController do

  # This should return the minimal set of attributes required to create a valid
  # YbClass. As you add validations to YbClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # YbClassesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all yb_classes as @yb_classes" do
      yb_class = YbClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:yb_classes).should eq([yb_class])
    end
  end

  describe "GET show" do
    it "assigns the requested yb_class as @yb_class" do
      yb_class = YbClass.create! valid_attributes
      get :show, {:id => yb_class.to_param}, valid_session
      assigns(:yb_class).should eq(yb_class)
    end
  end

  describe "GET new" do
    it "assigns a new yb_class as @yb_class" do
      get :new, {}, valid_session
      assigns(:yb_class).should be_a_new(YbClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested yb_class as @yb_class" do
      yb_class = YbClass.create! valid_attributes
      get :edit, {:id => yb_class.to_param}, valid_session
      assigns(:yb_class).should eq(yb_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new YbClass" do
        expect {
          post :create, {:yb_class => valid_attributes}, valid_session
        }.to change(YbClass, :count).by(1)
      end

      it "assigns a newly created yb_class as @yb_class" do
        post :create, {:yb_class => valid_attributes}, valid_session
        assigns(:yb_class).should be_a(YbClass)
        assigns(:yb_class).should be_persisted
      end

      it "redirects to the created yb_class" do
        post :create, {:yb_class => valid_attributes}, valid_session
        response.should redirect_to(YbClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved yb_class as @yb_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        YbClass.any_instance.stub(:save).and_return(false)
        post :create, {:yb_class => { "name" => "invalid value" }}, valid_session
        assigns(:yb_class).should be_a_new(YbClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        YbClass.any_instance.stub(:save).and_return(false)
        post :create, {:yb_class => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested yb_class" do
        yb_class = YbClass.create! valid_attributes
        # Assuming there are no other yb_classes in the database, this
        # specifies that the YbClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        YbClass.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => yb_class.to_param, :yb_class => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested yb_class as @yb_class" do
        yb_class = YbClass.create! valid_attributes
        put :update, {:id => yb_class.to_param, :yb_class => valid_attributes}, valid_session
        assigns(:yb_class).should eq(yb_class)
      end

      it "redirects to the yb_class" do
        yb_class = YbClass.create! valid_attributes
        put :update, {:id => yb_class.to_param, :yb_class => valid_attributes}, valid_session
        response.should redirect_to(yb_class)
      end
    end

    describe "with invalid params" do
      it "assigns the yb_class as @yb_class" do
        yb_class = YbClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YbClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => yb_class.to_param, :yb_class => { "name" => "invalid value" }}, valid_session
        assigns(:yb_class).should eq(yb_class)
      end

      it "re-renders the 'edit' template" do
        yb_class = YbClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        YbClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => yb_class.to_param, :yb_class => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested yb_class" do
      yb_class = YbClass.create! valid_attributes
      expect {
        delete :destroy, {:id => yb_class.to_param}, valid_session
      }.to change(YbClass, :count).by(-1)
    end

    it "redirects to the yb_classes list" do
      yb_class = YbClass.create! valid_attributes
      delete :destroy, {:id => yb_class.to_param}, valid_session
      response.should redirect_to(yb_classes_url)
    end
  end

end
